
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - '/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Basket {
			/**
			* Payment Provider

				Payment Provider Details
			* 
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#6) 
			*/
			fwpaymentprovider: string | null;

			/**
			* Payment Reference

				Payment Reference Details
			* 
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#13) 
			*/
			fwpaymentreference: string | null;

			/**
			* Payment URL

				Payment URL
			* 
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#20) 
			*/
			fwpaymenturl: string | null;

			/**
			* Order ID

				Order ID
			* 
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#27) 
			*/
			fworderid: string | null;

		}
		interface Order {
			/**
			* Payment Provider

				Payment Provider Details
			* 
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#39) 
			*/
			fwPaymentprovider: string | null;

			/**
			* Payment Reference

				Payment Reference Details
			* @group Firework - Firework Payment Details
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#46) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#72)
			*/
			fwpaymentreference: string | null;

			/**
			* Payment URL

				Payment URL
			* @group Firework - Firework Payment Details
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#53) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#73)
			*/
			fwpaymenturl: string | null;

			/**
			* Order ID

				Order ID
			* @group Firework - Firework Payment Details
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#60) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#74)
			*/
			fworderid: string | null;

		}
		interface SitePreferences {
			/**
			* Storefront URL
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#80) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#120)
			*/
			fireworkUniqueBMUID: string | null;

			/**
			* Contact Email
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#87) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#121)
			*/
			fireworkContactsEmail: string | null;

			/**
			* Curreny
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#94) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#119)
			*/
			fireworkSiteCurrency: string | null;

			/**
			* Site Title
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#101) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#122)
			*/
			fireworkSiteTitle: string | null;

			/**
			* Activate Purchase Track
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#108) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#123)
			*/
			fireworkEnablePurchaseTrack: boolean | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Storefront URL
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#80) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#120)
			*/
			(name: 'fireworkUniqueBMUID'): string | null;
			
			/**
			* Contact Email
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#87) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#121)
			*/
			(name: 'fireworkContactsEmail'): string | null;
			
			/**
			* Curreny
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#94) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#119)
			*/
			(name: 'fireworkSiteCurrency'): string | null;
			
			/**
			* Site Title
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#101) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#122)
			*/
			(name: 'fireworkSiteTitle'): string | null;
			
			/**
			* Activate Purchase Track
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#108) | [group](file:/Users/ruturajkalal/Work/salesforce/jul30/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#123)
			*/
			(name: 'fireworkEnablePurchaseTrack'): boolean | null;
			
	}
}