
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - '/Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Basket {
			/**
			* Payment Provider

				Payment Provider Details
			* 
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#6) 
			*/
			fwpaymentprovider: string | null;

			/**
			* Payment Reference

				Payment Reference Details
			* 
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#13) 
			*/
			fwpaymentreference: string | null;

			/**
			* Payment URL

				Payment URL
			* 
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#20) 
			*/
			fwpaymenturl: string | null;

			/**
			* Order ID

				Order ID
			* 
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#27) 
			*/
			fworderid: string | null;

		}
		interface Order {
			/**
			* Payment Provider

				Payment Provider Details
			* 
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#39) 
			*/
			fwPaymentprovider: string | null;

			/**
			* Payment Reference

				Payment Reference Details
			* @group Firework - Firework Payment Details
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#46) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#72)
			*/
			fwpaymentreference: string | null;

			/**
			* Payment URL

				Payment URL
			* @group Firework - Firework Payment Details
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#53) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#73)
			*/
			fwpaymenturl: string | null;

			/**
			* Order ID

				Order ID
			* @group Firework - Firework Payment Details
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#60) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#74)
			*/
			fworderid: string | null;

		}
		interface SitePreferences {
			/**
			* Storefront URL
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#80) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#143)
			*/
			fireworkUniqueBMUID: string | null;

			/**
			* Contact Email
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#87) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#144)
			*/
			fireworkContactsEmail: string | null;

			/**
			* Curreny
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#94) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#142)
			*/
			fireworkSiteCurrency: string | null;

			/**
			* Site Title
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#101) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#145)
			*/
			fireworkSiteTitle: string | null;

			/**
			* Image View Type

				Image type should be Comma separated values for e.g "large","medium"
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#108) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#146)
			*/
			fwImageviewtype: string | null;

			/**
			* GTIN

				Global Trade Item Number (GTIN) Field for Firework integration
			* 
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#116) 
			*/
			fwgtin: string | null;

			/**
			* Locale Id
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#124) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#147)
			*/
			fwLocaleId: string | null;

			/**
			* Activate Purchase Track
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#131) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#148)
			*/
			fireworkEnablePurchaseTrack: boolean | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Storefront URL
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#80) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#143)
			*/
			(name: 'fireworkUniqueBMUID'): string | null;
			
			/**
			* Contact Email
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#87) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#144)
			*/
			(name: 'fireworkContactsEmail'): string | null;
			
			/**
			* Curreny
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#94) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#142)
			*/
			(name: 'fireworkSiteCurrency'): string | null;
			
			/**
			* Site Title
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#101) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#145)
			*/
			(name: 'fireworkSiteTitle'): string | null;
			
			/**
			* Image View Type

				Image type should be Comma separated values for e.g "large","medium"
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#108) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#146)
			*/
			(name: 'fwImageviewtype'): string | null;
			
			/**
			* GTIN

				Global Trade Item Number (GTIN) Field for Firework integration
			* 
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#116) 
			*/
			(name: 'fwgtin'): string | null;
			
			/**
			* Locale Id
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#124) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#147)
			*/
			(name: 'fwLocaleId'): string | null;
			
			/**
			* Activate Purchase Track
			* @group fireworkDashboardConfig - Firework Dashboard Configuration
			* @source [attribute](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#131) | [group](file:///Users/ruturajkalal/Work/salesforce/github/salesforce/Metadata/Firework/meta/system-objecttype-extensions.xml#148)
			*/
			(name: 'fireworkEnablePurchaseTrack'): boolean | null;
			
	}
}